# Generated by Django 3.0.5 on 2020-04-03 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 3, 18, 49, 7, 558198, tzinfo=utc)),
        ),
    ]
