# Generated by Django 3.0.5 on 2020-04-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200405_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='userName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='userToken',
            field=models.CharField(max_length=520),
        ),
    ]
