# Generated by Django 3.0.5 on 2020-04-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200405_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=520)),
                ('password', models.CharField(max_length=520)),
            ],
        ),
    ]
