# Generated by Django 3.0.5 on 2020-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200406_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.CharField(default='user', max_length=520),
        ),
    ]
