# Generated by Django 3.0.5 on 2020-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_userdata_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='token',
            field=models.CharField(max_length=520),
        ),
    ]
