# Generated by Django 3.0.5 on 2020-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200406_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='postId',
            field=models.CharField(default='hfuierhf3r347r83473', max_length=520),
        ),
    ]
