# Generated by Django 3.0.5 on 2020-04-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='postId',
            new_name='postID',
        ),
    ]
