# Generated by Django 3.0.5 on 2020-04-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20200406_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creationTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
