# Generated by Django 3.0.5 on 2020-04-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_creationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creationTime',
            field=models.DateTimeField(),
        ),
    ]
