# Generated by Django 3.0.5 on 2020-04-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20200407_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creationTime',
        ),
    ]
