# Generated by Django 3.0.5 on 2020-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_remove_article_creationtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('postID', models.CharField(max_length=520)),
                ('userToken', models.CharField(max_length=520)),
                ('userName', models.CharField(max_length=120)),
            ],
        ),
    ]
